#coding:utf-8
from scrapy.item import Item, Field

class CrawlerItem(Item):
    id = Field()
    created = Field()
    updated = Field()
    
    domain = Field()
    site = Field()
    flow = Field()
    version = Field()
    url = Field()
    
    car_title = Field()
    car_brand = Field()
    car_series = Field()
    car_style = Field()
    car_type = Field()
    car_publish_logo = Field()
    standard_title = Field()
    vehicle_code = Field()
    car_type_score = Field()
    car_emission = Field()
    car_transmission = Field()
    car_outer_color = Field()
    car_inner_color = Field()
    car_age = Field()
    car_enter_time = Field()
    car_img_thumb = Field()
    car_images = Field()
    car_description = Field()
    car_mileage = Field()
    car_price = Field()
    purchase_price_refer = Field()
    source_province = Field()
    source_zone = Field()
    source_birth = Field()
    contact = Field()
    car_broker = Field()
    contact_phone = Field()
    contact_mobile = Field()
    contact_addr = Field()
    car_invoice = Field()
    car_surcharge = Field()
    car_tax_valid = Field()
    car_insur_validity = Field()
    car_inspection_date = Field()
    car_license_at = Field()
    status = Field()
    car_vin_code = Field()
    car_transfer_times = Field()
    shorturl = Field()
    process = Field()
    car_transaction_loc = Field()
    car_birth = Field()
    car_usage = Field()
    integrity = Field()
    car_care = Field()
    crawler = Field()
    car_img_server = Field()

    # It's will be removed when push to worker queue'
    _seq = Field()
    _max_seq = Field()

    def __str__(self):
        return '%s(%r)' % (self.__class__.__name__, dict(id=self['id'], url=self['url']))